from typing import Protocol, Optional
from aui_common.audio.types import PcmAudio
from aui_common.util.async_utils import CancellationToken

class AppContext(Protocol):
    async def say(self, text: str, wait: bool=False,
                  cancel: Optional[CancellationToken]=None) -> None: ...
    async def play(self, audio: PcmAudio, wait: bool=False,
                   cancel: Optional[CancellationToken]=None) -> None: ...
    async def stop_audio(self) -> None: ...

class App(Protocol):
    def init(self, ctx: AppContext) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
