from typing import Protocol, Optional
from aui_common.audio.types import PcmAudio
from aui_common.util.async_utils import CancellationToken

class AudioSink(Protocol):
    async def play(self, audio: PcmAudio, wait: bool=False,
                   cancel: Optional[CancellationToken]=None) -> None: ...
    async def stop(self) -> None: ...
    def is_busy(self) -> bool: ...

class AudioSource(Protocol):
    async def record(self, duration: float) -> PcmAudio: ...
